version: "3"

services:
  webvirtcloud:
    image: jinnyang/webvirtcloud:0.0.1
    build: 
      context: ./
      dockerfile: Dockerfile
      tags:
        - jinnyang/webvirtcloud:0.0.1
        - webvirtcloud:0.0.1
    container_name: webvirtcloud
    restart: unless-stopped
    # ports:
    #   - 80:80
    volumes:
      - /var/run/libvirt/:/var/run/libvirt/
      - /dev/pts/:/dev/pts/
      - webvirtcloud_data:/srv/webvirtcloud/data
    networks:
      kvm_network:
        # ipv4_address: 192.168.122.2
      application_network:
    extra_hosts:
      nas.local: 192.168.31.6
      nexus.nas.local: 192.168.31.6
      devpi.nas.local: 192.168.31.6

volumes:
  webvirtcloud_data:
    name: webvirtcloud_data

networks:
  kvm_network:
    name: kvm_network
    driver: macvlan
    driver_opts:
      parent: virbr0
      macvlan_mode: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.122.0/24
          gateway: 192.168.122.1
  application_network:
    name: application_network
    # driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 172.18.0.0/16
    #       gateway: 172.17.1.1

