version: "3"

services:
  webvirtcloud:
    image: webvirtcloud:0.0.1
    build: 
      context: ./
      dockerfile: Dockerfile
      tags:
        - webvirtcloud:0.0.1
    container_name: webvirtcloud
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/libvirt/:/var/run/libvirt/
      - /dev/pts/:/dev/pts/
      - webvirtcloud_data:/srv/webvirtcloud/data
      # - ./ssh:/var/www/.ssh
      # - ./webvirtcloud:/srv/webvirtcloud/webvirtcloud
    environment:
      KVM_HOST: "172.24.0.1"
      KVM_HOSTNAME: "localhost"
    networks:
      - kvm_network

volumes:
  webvirtcloud_data:
    name: webvirtcloud_data

networks:
  kvm_network:
    name: kvm_network
    driver: macvlan
    driver_opts:
      macvlan_mode: bridge
      parent: virbr0
