version: "3"

services:
  webvirtcloud:
    image: jinnyang/webvirtcloud:0.0.1
    build: 
      context: ./
      dockerfile: Dockerfile
      tags:
        - jinnyang/webvirtcloud:0.0.1
        - webvirtcloud:0.0.1
    container_name: webvirtcloud
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - /var/run/libvirt/:/var/run/libvirt/
      - /dev/pts/:/dev/pts/
      - webvirtcloud_data:/srv/webvirtcloud/data
    networks:
      - kvm_network
      - bridge
    extra_hosts:
      nas.local: 192.168.31.6
      nexus.nas.local: 192.168.31.6
      devpi.nas.local: 192.168.31.6

volumes:
  webvirtcloud_data:
    name: webvirtcloud_data

networks:
  kvm_network:
    name: kvm_network
    driver: macvlan
    driver_opts:
      macvlan_mode: bridge
      parent: virbr0
